account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


urlpatterns = [
    # poprzedni widok login view
    # path('login/', views.user_login, name='login'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('', views.dashboard, name='dashboard'),
    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/',auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('register/', views.register, name='register'),
    path('edit/', views.edit, name='edit'),
]

newsocial/urls.py
from django.contrib import admin
from django.urls import path, include

#from newsocial import settings

urlpatterns = [
    path('', include('services.urls')),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
]

#if settings.DEBUG:
    #urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

services/urls.py
from django.contrib import admin
from django.urls import path


from . import views




app_name = "services"
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('list', views.ServiceListView.as_view(), name='service_list'),
    path('detail/<pk>', views.ServiceDetailView.as_view(), name='service_detail'),
    path('category', views.CategoryView.as_view(), name='category'),
    path('create', views.ServiceCreateView.as_view(), name='service_create'),
    path('edit2/<pk>', views.UpdateServiceView.as_view(), name='service_edit'),
    path('delete/<pk>', views.ServiceDeleteView.as_view(), name='service_delete'),


]
    # path('add-to-basket', views.BasketCreateView.as_view(), name='add_to_basket'),
    # path('indeks', views.IndexView.as_view(), name ='index')
    # path('add-to-basket/<pk>', views.formularz_dodawania_do_koszyka, name='add_to_basket'),
    #path('zamowienie', views.do_koszyka, name='do_koszyka'),
    #path('<int:pk>', views.order, name = 'kosz'),
    #path('basket/<pk>', views.wysłanie_formularza_do_koszyka, name='basket'),
    # path('basket', views.BasketListView.as_view(), name='basket')

services/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(max_length=128)

    def __str__(self):
        return self.name


class Cities(models.Model):
    name = models.CharField(max_length=128)

    def __str__(self):
        return self.name

class Services(models.Model):
    title = models.CharField(max_length=128)
    photo = models.ImageField(upload_to='users/%Y/%m/%d', blank=True)
    rating = models.IntegerField(null=True)
    #rating = suma wszystkich ocen dzielona przez liczbe zakupow danej usługi
    bought = models.IntegerField(null=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.DO_NOTHING)
    price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='PLN')
    city = models.ForeignKey(Cities, on_delete=models.SET_NULL, null=True)
    deadline = models.DateTimeField()
    description = models.TextField(null=True, blank=True)

    class Meta:
        verbose_name = 'PLN'
    def __str__(self):
        return self.title



class Basket(models.Model):
    buyer = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    #buyer = models.ForeignKey('User', verbose_name="user", related_name="clients", on_delete=models.DO_NOTHING)
    #seller = models.ForeignKey(Services.owner, on_delete=models.CASCADE)
    id_service = models.ForeignKey(Services, on_delete=models.DO_NOTHING)
    ilosc = models.FloatField(max_length=3, null=True, blank=True)
    #price = models.ForeignKey(Services.price, on_delete=models.DO_NOTHING)

services/forms.py
from datetime import date

from django.forms import (
CharField, DateField, IntegerField, ModelForm, ImageField, ModelChoiceField, Textarea
)
from django.core.exceptions import ValidationError

from services.models import Category, Cities, Services, Basket

class FutureDateField(DateField):

    def validate(self, value):
        super().validate(value)
        if value <= date.today():
            raise ValidationError("Only future dates allowed here.")

    def clean(self, value):
        result = super().clean(value)
        return date(year=result.year, month=result.month, day=result.day)


class ServiceForm(ModelForm):

    class Meta:
        model = Services
        fields = '__all__'


class ServiceEditForm(ModelForm):
    class Meta:
        model = Services
        fields = ('title', 'photo', 'category', 'price', 'city', 'deadline', 'description')

#
# class BasketForm(ModelForm):
#     class Meta:
#         model = Basket
#         fields = ['id_service', 'ilosc']

services/views.py
from datetime import timezone
from logging import getLogger
from django.core.exceptions import PermissionDenied
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, CreateView, DeleteView, UpdateView, DetailView
from django.urls import reverse_lazy

from services.models import Services, Category, Basket
from services.forms import ServiceForm, ServiceEditForm
from services.templatetags.service_extras import service_format

LOGGER = getLogger()

class ServiceListView(ListView):
    template_name = 'service_list.html'
    model = Services


class ServiceDetailView(DetailView):
    template_name = 'service_detail.html'
    model = Services

class ServiceDeleteView(DeleteView):
    template_name = 'service_confirm_delete.html'
    model = Services
    success_url = reverse_lazy('service:service_list')


class ServiceCreateView(CreateView):
    template_name = 'form.html'
    form_class = ServiceForm
    success_url = reverse_lazy('service:service_list')

    def form_valid(self, form):
        service = form.save(commit=False)
        service.user = self.request.user
        service.save()
        super().form_valid(form)

    def form_invalid(self, form):
        LOGGER.warning('User provided invalid data.')
        return super().form_invalid(form)


class ServiceView(ListView):
    template_name = 'index.html'
    model = Services


class CategoryView(ListView):
    template_name = 'category.html'
    model = Category


# @login_required
# def edit(request, pk):
#     service = Services.objects.filter(id=pk).first()
#     if request.method == 'POST':
#         service_form = ServiceEditForm(instance=service, data=request.POST, files=request.FILES)
#         if service_form.is_valid():
#             service_form.save()
#     else:
#         service_form = ServiceEditForm(instance=service)
#
#     return render(request, 'service_edit.html', {'service_form': service_form})


class UpdateServiceView(UpdateView):
    template_name = "form.html"
    form_class = ServiceForm
    model = Services
    success_url = reverse_lazy('service:service_list')

    def get_object(self, queryset=None,):
        service = super().get_object(queryset)
        if service.owner != self.request.user:
            raise PermissionDenied()
        return service

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context["service_form"] = context["form"]
        return context

class IndexView(ServiceListView):
    template_name = 'index.html'


"""
Koszyk


def add_to_basket(request):
    print('Funkcja uruchomiona')
    # if request.method == "POST":
    #     basket = Basket.objects.filter(buyer=request.user).first()
    #     basket.items.add(Services.objects.filter(id=pk).first())
    buyer = request.user
    id_service = request.service.pk
    return render(request, 'basket.html', {'object_list': basket_id_user, 'service_obj': basket_id_service})

class BasketCreate(CreateView):
        template_name = 'form.html'
        form_class = BasketForm
        success_url = reverse_lazy('service_list')

        def form_valid(self, form):
            basket = form.save(commit=False)
            basket.user = self.request.user
            # basket.id_service = Services.objects.filter(id=pk).first()
            basket.save()
            super().form_valid(form)

        def form_invalid(self, form):
            LOGGER.warning('User provided invalid data.')
            return super().form_invalid(form)


def wysłanie_formularza_do_koszyka(request, pk):
    service = Services.objects.filter(id=pk).first()
    #buyer = request.user.username
    basket = Basket()
    if request.method == 'POST':
        basket.id_service.add(service)
        basket_finish = AddToBasketForm(instance=basket, data=request.POST, files=request.FILES)
        if basket_finish.is_valid():
            basket_finish.save()
    else:
        basket_finish = AddToBasketForm(instance=basket)
    return render(request, 'basket.html', {'basket_form': basket_finish, 'basket': basket })




class BasketListView(ListView):
    if request.method == "POST":
        basket.id_service.add(Services.objects.filter(id=pk).first())
    template_name = 'basket.html'
    model = Basket

def koszyk(request, *args, **kwargs):
    return render(request, "basket.html", {})


def order(request):
    basket = Basket.objects(...).first()
    # Create order
    basket.items.clear()# do czyszczenia

class BasketCreateView(CreateView):
    template_name = 'form.html'
    form_class = BasketForm
    success_url = reverse_lazy('services:service_list')

    def form_valid(self, form):
        order = form.save(commit=False)
        order.user = self.request.user
        order.save()
        super().form_valid(form)
        #return HttpResponse("Here's the text of the Web page.")

    def form_invalid(self, form):
        LOGGER.warning('User provided invalid data.')
        return super().form_invalid(form)

def do_koszyka(request):
    if request.method == "POST":
        form = BasketForm(request.POST)
        if form.is_valid():
            zamowienie = form.save(commit=False)
            zamowienie.data_publikacji = timezone.now()
            zamowienie.save()
            return redirect('services:kosz', pk=zamowienie.pk)
        else:
            form = BasketForm()
        return render(request, 'basket.html', {'form': form})

def order(request, pk):
    zamowienie = get_object_or_404(Basket, pk=pk)
    return render(request, 'basket.html', {'zamowienie': zamowienie})

    service = Services.objects.filter(id=pk).first()
    #buyer = request.user.username
    basket = Basket()
    if request.method == 'POST':
        basket.id_service.add(service)
        basket_finish = AddToBasketForm(instance=basket, data=request.POST, files=request.FILES)
        if basket_finish.is_valid():
            basket_finish.save()
    else:
        basket_finish = AddToBasketForm(instance=basket)
    return render(request, 'basket.html', {'basket_form': basket_finish, 'basket': basket })
"""

services/templates/add_to_basket.html
{% extends 'base.html' %}
{% load service_extras %}

{% block content %}

<ul>
</ul>

<!--    <form action="." method="post" enctype="multipart/form-data">-->
<!--        {{ basket_form.as_p }}-->
<!--        {% csrf_token %}-->
<!--        <p><input type="submit" value="Dodaj usługę do koszyka"></p>-->
<!--    </form>-->

{% endblock %}

services/templates/base.html
{% load bootstrap4 %}
<!--{% load static %}-->

<html {% if LANGUAGE_CODE %}lang="{{ LANGUAGE_CODE }}"{% endif %}>

  <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <title>Lista usług</title>
      {% block styles %}{% bootstrap_css %}{% endblock %}
      {% block scripts %}{% bootstrap_javascript jquery='full' %}{% endblock %}
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container fixed">
        <a class="navbar-brand" href="list">Lista Uslug</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-item nav-link active" href="account/">
              Profil
             </a>
         </li>
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Logowanie</a>
    <div class="dropdown-menu">
      <a class="dropdown-item" href="account/login/">Zaloguj się</a>
      <div class="dropdown-divider"></div>
      <a class="dropdown-item" href="account/register/">Zarejestruj się</a>
    </div>
  </li>
  <li class="nav-item">
          </div>
        </div>
      </div>
    </nav>
    <div class="container">
      <div class="jumbotron">
        {% block content %}{% endblock %}
      </div>
    </div>
  </body>

</html>

services/templates/basket.html
{% extends 'base.html' %}
{% load service_extras %}

{% block content %}

    <title>LISTA ZAKUPÓW</title>
<div class="post">
    {% if zamowienie.data_publikacji %}
    <div class="date">
        {{ zamowienie.data_publikacji}}
    </div>
    {% ednif %}

   <a href="{% url services:service_edit" pk="zamowienie.pk %}">
       <span></span>
   </a>
<p>Kupujący: {{ zamowienie.ilosc}}</p>
<p>Produkt: {{}}</p>

</div>

{% endblock content %}

services/templates/category.html
{% extends 'base.html' %}

{% block content %}
<h1> Choose the category</h1>
<ul>
    {% for category in object_list %}
    <li>
        {{ category.name }}
    </li>
    {% endfor %}
</ul>
{% endblock %}

services/templates/form.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
        <input type="submit" value="Submit" class='btn btn-primary'>
        {% endbuttons %}
    </form>
{% endblock %}

services/templates/index.html
{% extends 'base.html' %}
{% load service_extras %}

{% block content %}
<h1> Welcome to our NewSocial app!</h1>
<ul>
    {% for service in object_list %}
    <li>
        {% service_format service %}
    </li>
    {% endfor %}
</ul>
{% endblock %}

services/templates/service_confirm_delete.html
{% extends "base.html" %}

{% block content %}

    <form method="post">
        {% csrf_token %}
        <p>Jestes pewny że usuwasz '{{object.title}}' z bazy?</p>
        <p><input type="submit" value="Usuń"></p>
    </form>
{% endblock %}

services/templates/service_detail.html
{% extends 'base.html' %}
{% load service_extras %}

{% block content %}
    {{object|attr_as_p:'title' }}
    {{object|attr_as_p:'photo' }}
    {{object|attr_as_p:'rating' }}
    {{object|attr_as_p:'bought' }}
    {{object|attr_as_p:'owner' }}
    {{object|attr_as_p:'category' }}
    {{object|attr_as_p:'price' }}
    {{object|attr_as_p:'city' }}
    {{object|attr_as_p:'deadline' }}
    {{object|attr_as_p:'description' }}
{% endblock %}>

services/templates/service_edit.html
{% extends "base.html" %}

{% block title %}Edytuj swoją usługę{% endblock %}
{% block content %}
    <h1>Edycja konta</h1>
    <p>Ustawienia usługi możesz zmienić za pomocą poniższego formularza:</p>
    <form action="." method="post" enctype="multipart/form-data">
        {{ service_form.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="Zapisz zmiany"></p>
    </form>
{% endblock %}

services/templates/service_list.html
{% extends 'base.html' %}
{% load service_extras %}

{% block content %}
<h1> Welcome to our NewSocial app!</h1>
<ul>
    {% for service in object_list %}
    <li>
<!--        {% service_format service short=True %}-->
        <a href="{% url 'services:service_detail' service.pk %}">{{ service.title }}</a>
        ({{service.price}}) - {{service.rating}} {{service.category.name}}
        <a href="{% url 'services:service_edit' service.pk %}">Edit</a>
        <a href="{% url 'services:service_delete' service.pk %}">Delete</a>
<!--        <a>add to basket</a>-->
    </li>
    {% endfor %}
</ul>
{% endblock %}

services/templates/services.html
{% extends 'base.html' %}
{% load service_extras %}

{% block content %}
<h1> Welcome to our NewSocial app!</h1>
<ul>
    {% for service in object_list %}
    <li>
        {% service_format service %}
    </li>
    {% endfor %}
</ul>
{% endblock %}